language: generic

services:
  - postgresql

addons:
  postgresql: "9.3"

env: PG_DATABASE=travis_test PG_USER=postgres YEAR=2016

before_install:
  - psql -U $PG_USER -c "create database $PG_DATABASE"

install:
  - travis_retry make fars-$YEAR.zip

script:
  - make -e init
  - make -e load
