language: generic

services:
  - postgresql

addons:
  postgresql: "9.3"

env: PGDATABASE=travis_test PGUSER=postgres YEAR=2016

before_install:
  - psql -U $PGUSER -c "create database $PGDATABASE"

install:
  - travis_retry make fars-$YEAR.zip

script:
  - make -e init
  - make -e load
