-- todo: emergency use

SET search_path to :schema;

CREATE TABLE state (
    state int primary key,
    name text,
    fips char(2)
);

CREATE TABLE accident (
    state integer,  
    statename character varying(127),
    st_case integer PRIMARY KEY,
    ve_total integer,
    ve_forms integer,
    pvh_invl integer,
    peds integer,
    pernotmvit integer,
    permvit integer,
    persons integer,
    county integer,
    countyname  character varying(127),
    city integer,
    cityname  character varying(127),
    day integer,
    dayname  character varying(127),
    month integer,
    monthname  character varying(127),
    year integer,
    day_week integer,
    day_weekname  character varying(127),
    hour integer,
    hourname  character varying(127),
    minute integer,
    minutename  character varying(127),
    nhs integer,
    nhsname  character varying(127),
    route integer,
    routename  character varying(127),
    tway_id text,
    tway_id2 text,
    rur_urb integer,
    rur_urbname  character varying(127),
    func_sys integer,
    func_sysname  character varying(127),
    rd_owner integer,
    rd_ownername  character varying(127),
    milept integer,
    mileptname  character varying(127),
    latitude double precision,
    latitudename  character varying(127),
    longitud double precision,
    longitudname  character varying(127),
    sp_jur integer,
    sp_jurname  character varying(127),
    harm_ev integer,
    harm_evname  character varying(255),
    man_coll integer,
    man_collname  character varying(127),
    reljct1 integer,
    reljct1name  character varying(127),
    reljct2 integer,
    reljct2name  character varying(127),
    typ_int integer,
    typ_intname  character varying(127),
    wrk_zone integer,
    wrk_zonename  character varying(127),
    rel_road integer,
    rel_roadname  character varying(127),
    lgt_cond integer,
    lgt_condname  character varying(127),
    -- weather1 integer,
    -- weather2 integer,
    weather integer,
    weathername  character varying(127),
    sch_bus integer,
    sch_busname  character varying(127),
    rail text,
    railname  character varying(127),
    not_hour integer,
    not_hourname  character varying(127),
    not_min integer,
    not_minname  character varying(127),
    arr_hour integer,
    arr_hourname  character varying(127),
    arr_min integer,
    arr_minname  character varying(127),
    hosp_hr integer,
    hosp_hrname  character varying(127),
    hosp_mn integer,
    hosp_mnname  character varying(127),
    -- cf1 integer,
    -- cf2 integer,
    -- cf3 integer,
    fatals integer,
    drunk_dr integer
);
-- these changes were necessary because data format from NHTSA changed dramatically around 2020 (and reflected back, and data was re-released)
-- when doing copy, needed to set encoding on command: COPY accident FROM '/home/ed/getfars/accident.CSV' DELIMITER ',' encoding 'windows-1251' CSV HEADER;

CREATE TABLE cevent (
    state integer,
    st_case integer,
    eventnum integer,
    vnumber1 integer,
    aoi1 integer,
    soe integer,
    vnumber2 integer,
    aoi2 integer,
    constraint cevent_pk primary key (st_case, eventnum)
);

CREATE TABLE damage (
    state integer,
    st_case integer,
    veh_no integer,
    mdareas integer
);

CREATE TABLE distract (
    state integer,
    st_case integer,
    veh_no integer,
    mdrdstrd integer
);

CREATE TABLE drimpair (
    state integer,
    st_case integer,
    veh_no integer,
    drimpair integer
);

CREATE TABLE factor (
    state integer,
    st_case integer,
    veh_no integer,
    mfactor integer
);

CREATE TABLE maneuver (
    state integer,
    st_case integer,
    veh_no integer,
    mdrmanav integer
);

CREATE TABLE nmcrash (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    mtm_crsh integer
);

CREATE TABLE nmimpair (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    nmimpair integer
);

CREATE TABLE nmprior (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    mpr_act integer
);

CREATE TABLE parkwork (
    state integer,
    st_case integer,
    veh_no integer,
    pve_forms integer,
    pnumoccs integer,
    pday integer,
    pmonth integer,
    phour integer,
    pminute integer,
    pharm_ev integer,
    pman_coll integer,
    ptype integer,
    phit_run integer,
    preg_stat integer,
    powner integer,
    pmake integer,
    pmodel integer,
    pmak_mod integer,
    pbodytyp integer,
    pmodyear integer,
    pvin text,
    pvin_1 text,
    pvin_2 text,
    pvin_3 text,
    pvin_4 text,
    pvin_5 text,
    pvin_6 text,
    pvin_7 text,
    pvin_8 text,
    pvin_9 text,
    pvin_10 text,
    pvin_11 text,
    pvin_12 text,
    ptrailer integer,
    pmcarr_i1 text,
    pmcarr_i2 text,
    pmcarr_id text,
    pgvwr integer,
    pv_config integer,
    pcargtyp integer,
    phaz_inv integer,
    phazplac integer,
    phaz_id integer,
    phaz_cno integer,
    phaz_rel integer,
    pbus_use integer,
    psp_use integer,
    pem_use integer,
    punderide integer,
    pimpact1 integer,
    pveh_sev integer,
    ptowed integer,
    pm_harm integer,
    pveh_sc1 integer,
    pveh_sc2 integer,
    pfire integer,
    pdeaths integer,
    ptrlr1vin text,
    ptrlr2vin text,
    ptrlr3vin text,
    constraint parkwork_pk primary key (st_case, veh_no)
);

CREATE TABLE pbtype (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    pbptype integer,
    pbage integer,
    pbsex integer,
    pbcwalk integer,
    pbswalk integer,
    pbszone integer,
    pedctype integer,
    bikectype integer,
    pedloc integer,
    bikeloc integer,
    pedpos integer,
    bikepos integer,
    peddir integer,
    bikedir integer,
    motdir integer,
    motman integer,
    pedleg integer,
    pedsnr text,
    pedcgp integer,
    bikecgp integer,
    constraint pbtype_pk primary key (st_case, per_no)
);

CREATE TABLE person (
    state integer,
    st_case integer,
    ve_forms integer,
    veh_no integer,
    per_no integer,
    str_veh integer,
    county integer,
    day integer,
    month integer,
    hour integer,
    minute integer,
    rur_urb integer,
    func_sys integer,
    harm_ev integer,
    man_coll integer,
    sch_bus integer,
    make integer,
    mak_mod integer,
    body_typ integer,
    mod_year integer,
    tow_veh integer,
    spec_use integer,
    emer_use integer,
    rollover integer,
    impact1 integer,
    fire_exp integer,
    age integer,
    sex integer,
    per_typ integer,
    inj_sev integer,
    seat_pos integer,
    rest_use integer,
    rest_mis integer,
    air_bag integer,
    ejection integer,
    ej_path integer,
    extricat integer,
    drinking integer,
    alc_det integer,
    alc_status integer,
    atst_typ integer,
    alc_res integer,
    drugs integer,
    drug_det integer,
    dstatus integer,
    drugtst1 integer,
    drugtst2 integer,
    drugtst3 integer,
    drugres1 integer,
    drugres2 integer,
    drugres3 integer,
    hospital integer,
    doa integer,
    death_da integer,
    death_mo integer,
    death_yr integer,
    death_hr integer,
    death_mn integer,
    death_tm integer,
    lag_hrs integer,
    lag_mins integer,
    p_sf1 integer,
    p_sf2 integer,
    p_sf3 integer,
    work_inj integer,
    hispanic integer ,
    race integer,
    location integer,
    constraint person_pk primary key (st_case, veh_no, per_no)
);

CREATE TABLE safetyeq (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    nmhelmet integer,
    nmpropad integer,
    nmothpro integer,
    nmrefclo integer,
    nmlight integer,
    nmothpre integer
);

-- This is the generated table code using the sqlite3 method; open the csv in sqlite, and dump the schema
CREATE TABLE vehicle (
   "STATE" TEXT,
  "STATENAME" TEXT,
  "ST_CASE" integer,
  "VEH_NO"  integer,
  "VE_FORMS" TEXT,
  "NUMOCCS" TEXT,
  "NUMOCCSNAME" TEXT,
  "DAY" TEXT,
  "DAYNAME" TEXT,
  "MONTH" TEXT,
  "MONTHNAME" TEXT,
  "HOUR" TEXT,
  "HOURNAME" TEXT,
  "MINUTE" TEXT,
  "MINUTENAME" TEXT,
  "HARM_EV" TEXT,
  "HARM_EVNAME" TEXT,
  "MAN_COLL" TEXT,
  "MAN_COLLNAME" TEXT,
  "UNITTYPE" TEXT,
  "UNITTYPENAME" TEXT,
  "HIT_RUN" TEXT,
  "HIT_RUNNAME" TEXT,
  "REG_STAT" TEXT,
  "REG_STATNAME" TEXT,
  "OWNER" TEXT,
  "OWNERNAME" TEXT,
  "MAKE" TEXT,
  "MAKENAME" TEXT,
  "MODEL" TEXT,
  "MAK_MOD" TEXT,
  "MAK_MODNAME" TEXT,
  "BODY_TYP" TEXT,
  "BODY_TYPNAME" TEXT,
  "MOD_YEAR" TEXT,
  "MOD_YEARNAME" TEXT,
  "VIN" TEXT,
  "VINNAME" TEXT,
  "VIN_1" TEXT,
  "VIN_2" TEXT,
  "VIN_3" TEXT,
  "VIN_4" TEXT,
  "VIN_5" TEXT,
  "VIN_6" TEXT,
  "VIN_7" TEXT,
  "VIN_8" TEXT,
  "VIN_9" TEXT,
  "VIN_10" TEXT,
  "VIN_11" TEXT,
  "VIN_12" TEXT,
  "TOW_VEH" TEXT,
  "TOW_VEHNAME" TEXT,
  "J_KNIFE" TEXT,
  "J_KNIFENAME" TEXT,
  "MCARR_I1" TEXT,
  "MCARR_I1NAME" TEXT,
  "MCARR_I2" TEXT,
  "MCARR_I2NAME" TEXT,
  "MCARR_ID" TEXT,
  "MCARR_IDNAME" TEXT,
  "V_CONFIG" TEXT,
  "V_CONFIGNAME" TEXT,
  "CARGO_BT" TEXT,
  "CARGO_BTNAME" TEXT,
  "HAZ_INV" TEXT,
  "HAZ_INVNAME" TEXT,
  "HAZ_PLAC" TEXT,
  "HAZ_PLACNAME" TEXT,
  "HAZ_ID" TEXT,
  "HAZ_IDNAME" TEXT,
  "HAZ_CNO" TEXT,
  "HAZ_CNONAME" TEXT,
  "HAZ_REL" TEXT,
  "HAZ_RELNAME" TEXT,
  "BUS_USE" TEXT,
  "BUS_USENAME" TEXT,
  "SPEC_USE" TEXT,
  "SPEC_USENAME" TEXT,
  "EMER_USE" TEXT,
  "EMER_USENAME" TEXT,
  "TRAV_SP" TEXT,
  "TRAV_SPNAME" TEXT,
  "UNDERIDE" TEXT,
  "UNDERIDENAME" TEXT,
  "ROLLOVER" TEXT,
  "ROLLOVERNAME" TEXT,
  "ROLINLOC" TEXT,
  "ROLINLOCNAME" TEXT,
  "IMPACT1" TEXT,
  "IMPACT1NAME" TEXT,
  "DEFORMED" TEXT,
  "DEFORMEDNAME" TEXT,
  "TOWED" TEXT,
  "TOWEDNAME" TEXT,
  "M_HARM" TEXT,
  "M_HARMNAME" TEXT,
  "FIRE_EXP" TEXT,
  "FIRE_EXPNAME" TEXT,
  "DR_PRES" TEXT,
  "DR_PRESNAME" TEXT,
  "L_STATE" TEXT,
  "L_STATENAME" TEXT,
  "DR_ZIP" TEXT,
  "DR_ZIPNAME" TEXT,
  "L_STATUS" TEXT,
  "L_STATUSNAME" TEXT,
  "L_TYPE" TEXT,
  "L_TYPENAME" TEXT,
  "CDL_STAT" TEXT,
  "CDL_STATNAME" TEXT,
  "L_ENDORS" TEXT,
  "L_ENDORSNAME" TEXT,
  "L_COMPL" TEXT,
  "L_COMPLNAME" TEXT,
  "L_RESTRI" TEXT,
  "L_RESTRINAME" TEXT,
  "DR_HGT" TEXT,
  "DR_HGTNAME" TEXT,
  "DR_WGT" TEXT,
  "DR_WGTNAME" TEXT,
  "PREV_ACC" TEXT,
  "PREV_ACCNAME" TEXT,
  "PREV_SUS1" TEXT,
  "PREV_SUS1NAME" TEXT,
  "PREV_SUS2" TEXT,
  "PREV_SUS2NAME" TEXT,
  "PREV_SUS3" TEXT,
  "PREV_SUS3NAME" TEXT,
  "PREV_DWI" TEXT,
  "PREV_DWINAME" TEXT,
  "PREV_SPD" TEXT,
  "PREV_SPDNAME" TEXT,
  "PREV_OTH" TEXT,
  "PREV_OTHNAME" TEXT,
  "FIRST_MO" TEXT,
  "FIRST_MONAME" TEXT,
  "FIRST_YR" TEXT,
  "FIRST_YRNAME" TEXT,
  "LAST_MO" TEXT,
  "LAST_MONAME" TEXT,
  "LAST_YR" TEXT,
  "LAST_YRNAME" TEXT,
  "SPEEDREL" TEXT,
  "SPEEDRELNAME" TEXT,
  "VTRAFWAY" TEXT,
  "VTRAFWAYNAME" TEXT,
  "VNUM_LAN" TEXT,
  "VNUM_LANNAME" TEXT,
  "VSPD_LIM" TEXT,
  "VSPD_LIMNAME" TEXT,
  "VALIGN" TEXT,
  "VALIGNNAME" TEXT,
  "VPROFILE" TEXT,
  "VPROFILENAME" TEXT,
  "VPAVETYP" TEXT,
  "VPAVETYPNAME" TEXT,
  "VSURCOND" TEXT,
  "VSURCONDNAME" TEXT,
  "VTRAFCON" TEXT,
  "VTRAFCONNAME" TEXT,
  "VTCONT_F" TEXT,
  "VTCONT_FNAME" TEXT,
  "P_CRASH1" TEXT,
  "P_CRASH1NAME" TEXT,
  "P_CRASH2" TEXT,
  "P_CRASH2NAME" TEXT,
  "P_CRASH3" TEXT,
  "P_CRASH3NAME" TEXT,
  "PCRASH4" TEXT,
  "PCRASH4NAME" TEXT,
  "PCRASH5" TEXT,
  "PCRASH5NAME" TEXT,
  "ACC_TYPE" TEXT,
  "ACC_TYPENAME" TEXT,
  "DEATHS" TEXT,
  "DR_DRINK" TEXT,
  "DR_DRINKNAME" TEXT,
  "TRLR1VIN" TEXT,
  "TRLR1VINNAME" TEXT,
  "TRLR2VIN" TEXT,
  "TRLR2VINNAME" TEXT,
  "TRLR3VIN" TEXT,
  "TRLR3VINNAME" TEXT,
  "VPICMAKE" TEXT,
  "VPICMAKENAME" TEXT,
  "VPICMODEL" TEXT,
  "VPICMODELNAME" TEXT,
  "VPICBODYCLASS" TEXT,
  "VPICBODYCLASSNAME" TEXT,
  "ICFINALBODY" TEXT,
  "ICFINALBODYNAME" TEXT,
  "GVWR_FROM" TEXT,
  "GVWR_FROMNAME" TEXT,
  "GVWR_TO" TEXT,
  "GVWR_TONAME" TEXT,
  "TRLR1GVWR" TEXT,
  "TRLR1GVWRNAME" TEXT,
  "TRLR2GVWR" TEXT,
  "TRLR2GVWRNAME" TEXT,
  "TRLR3GVWR" TEXT,
  "TRLR3GVWRNAME" TEXT,
    constraint vehicle_pk primary key ("ST_CASE", "VEH_NO")
);

CREATE TABLE vevent (
    state integer,
    st_case integer,
    eventnum integer,
    veh_no integer,
    veventnum integer,
    vnumber1 integer,
    aoi1 integer,
    soe integer,
    vnumber2 integer,
    aoi2 integer,
    constraint vevent_pk primary key (st_case, veh_no, eventnum)
);

CREATE TABLE vindecode (
    state integer,
    st_case integer,
    veh_no integer,
    ncicmake text,
    vinyear integer,
    vehtype text,
    vehtype_t text,
    vinmake_t text,
    vinmodel_t text,
    vintrim_t text,
    vintrim1_t text,
    vintrim2_t text,
    vintrim3_t text,
    vintrim4_t text,
    bodystyl text,
    bodystyl_t text,
    doors integer,
    wheels integer,
    drivwhls integer,
    mfg text,
    mfg_t text,
    displci integer,
    displcc integer,
    cylndrs text,
    cycles integer,
    fuel text,
    fuel_t text,
    fuelinj text,
    fuelinj_t text,
    carbtype text,
    carbtype_t text,
    carbbrls text,
    gvwrange integer,
    gvwrange_t text,
    whlbsh double precision,
    whlblg double precision,
    tiredesc_f text,
    psi_f integer,
    tiresz_f text,
    tiresz_f_t text,
    tiredesc_r text,
    psi_r integer,
    rearsize text,
    rearsize_t text,
    tonrating text,
    shipweight integer,
    msrp integer,
    drivetyp text,
    drivetyp_t text,
    salectry text,
    salectry_t text,
    abs text,
    abs_t text,
    security text,
    security_t text,
    drl text,
    drl_t text,
    rstrnt text,
    rstrnt_t text,
    tkcab text,
    tkcab_t text,
    tkaxlef text,
    tkaxlef_t text,
    tkaxler text,
    tkaxler_t text,
    tkbrak text,
    tkbrak_t text,
    engmfg text,
    engmfg_t text,
    engmodel text,
    tkduty text,
    tkduty_t text,
    tkbedl text,
    tkbedl_t text,
    segmnt text,
    segmnt_t text,
    plant text,
    plntctry_t text,
    plntcity text,
    plntctry text,
    plntstat text,
    plntstat_t text,
    origin text,
    origin_t text,
    dispclmt double precision,
    blocktype text,
    enghead text,
    enghead_t text,
    vlvclndr integer,
    vlvtotal integer,
    engvincd text,
    incomplt boolean,
    battyp text,
    battyp_t text,
    batkwrtg text,
    batvolt double precision,
    supchrgr text,
    supchrgr_t text,
    turbo text,
    turbo_t text,
    engvvt text,
    mcyusage text,
    mcyusage_t text,
    constraint vindecode_pk primary key (st_case, veh_no)
);

CREATE TABLE violatn (
    state integer,
    st_case integer,
    veh_no integer,
    mviolatn integer
);

CREATE TABLE vision (
    state integer,
    st_case integer,
    veh_no integer,
    mvisobsc integer
);

CREATE TABLE vsoe (
    state integer,
    st_case integer,
    veh_no integer,
    veventnum integer,
    soe integer,
    aoi integer,
    constraint vsoe_pk primary key (st_case, veh_no, veventnum)
);
