-- todo: emergency use

SET search_path to :schema;

CREATE TABLE state (
    state int primary key,
    name text,
    fips char(2)
);

CREATE TABLE accident (
    state integer,  
    statename character varying(127),
    st_case integer PRIMARY KEY,
    ve_total integer,
    ve_forms integer,
    pvh_invl integer,
    peds integer,
    pernotmvit integer,
    permvit integer,
    persons integer,
    county integer,
    countyname  character varying(127),
    city integer,
    cityname  character varying(127),
    day integer,
    dayname  character varying(127),
    month integer,
    monthname  character varying(127),
    year integer,
    day_week integer,
    day_weekname  character varying(127),
    hour integer,
    hourname  character varying(127),
    minute integer,
    minutename  character varying(127),
    nhs integer,
    nhsname  character varying(127),
    route integer,
    routename  character varying(127),
    tway_id text,
    tway_id2 text,
    rur_urb integer,
    rur_urbname  character varying(127),
    func_sys integer,
    func_sysname  character varying(127),
    rd_owner integer,
    rd_ownername  character varying(127),
    milept integer,
    mileptname  character varying(127),
    latitude double precision,
    latitudename  character varying(127),
    longitud double precision,
    longitudname  character varying(127),
    sp_jur integer,
    sp_jurname  character varying(127),
    harm_ev integer,
    harm_evname  character varying(255),
    man_coll integer,
    man_collname  character varying(127),
    reljct1 integer,
    reljct1name  character varying(127),
    reljct2 integer,
    reljct2name  character varying(127),
    typ_int integer,
    typ_intname  character varying(127),
    wrk_zone integer,
    wrk_zonename  character varying(127),
    rel_road integer,
    rel_roadname  character varying(127),
    lgt_cond integer,
    lgt_condname  character varying(127),
    -- weather1 integer,
    -- weather2 integer,
    weather integer,
    weathername  character varying(127),
    sch_bus integer,
    sch_busname  character varying(127),
    rail text,
    railname  character varying(127),
    not_hour integer,
    not_hourname  character varying(127),
    not_min integer,
    not_minname  character varying(127),
    arr_hour integer,
    arr_hourname  character varying(127),
    arr_min integer,
    arr_minname  character varying(127),
    hosp_hr integer,
    hosp_hrname  character varying(127),
    hosp_mn integer,
    hosp_mnname  character varying(127),
    -- cf1 integer,
    -- cf2 integer,
    -- cf3 integer,
    fatals integer,
    drunk_dr integer
);
-- these changes were necessary because data format from NHTSA changed dramatically around 2020 (and reflected back, and data was re-released)
-- when doing copy, needed to set encoding on command: COPY accident FROM '/home/ed/getfars/accident.CSV' DELIMITER ',' encoding 'windows-1251' CSV HEADER;

CREATE TABLE cevent (
    state integer,
    st_case integer,
    eventnum integer,
    vnumber1 integer,
    aoi1 integer,
    soe integer,
    vnumber2 integer,
    aoi2 integer,
    constraint cevent_pk primary key (st_case, eventnum)
);

CREATE TABLE damage (
    state integer,
    st_case integer,
    veh_no integer,
    mdareas integer
);

CREATE TABLE distract (
    state integer,
    st_case integer,
    veh_no integer,
    mdrdstrd integer
);

CREATE TABLE drimpair (
    state integer,
    st_case integer,
    veh_no integer,
    drimpair integer
);

CREATE TABLE factor (
    state integer,
    st_case integer,
    veh_no integer,
    mfactor integer
);

CREATE TABLE maneuver (
    state integer,
    st_case integer,
    veh_no integer,
    mdrmanav integer
);

CREATE TABLE nmcrash (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    mtm_crsh integer
);

CREATE TABLE nmimpair (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    nmimpair integer
);

CREATE TABLE nmprior (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    mpr_act integer
);

CREATE TABLE parkwork (
    state integer,
    st_case integer,
    veh_no integer,
    pve_forms integer,
    pnumoccs integer,
    pday integer,
    pmonth integer,
    phour integer,
    pminute integer,
    pharm_ev integer,
    pman_coll integer,
    ptype integer,
    phit_run integer,
    preg_stat integer,
    powner integer,
    pmake integer,
    pmodel integer,
    pmak_mod integer,
    pbodytyp integer,
    pmodyear integer,
    pvin text,
    pvin_1 text,
    pvin_2 text,
    pvin_3 text,
    pvin_4 text,
    pvin_5 text,
    pvin_6 text,
    pvin_7 text,
    pvin_8 text,
    pvin_9 text,
    pvin_10 text,
    pvin_11 text,
    pvin_12 text,
    ptrailer integer,
    pmcarr_i1 text,
    pmcarr_i2 text,
    pmcarr_id text,
    pgvwr integer,
    pv_config integer,
    pcargtyp integer,
    phaz_inv integer,
    phazplac integer,
    phaz_id integer,
    phaz_cno integer,
    phaz_rel integer,
    pbus_use integer,
    psp_use integer,
    pem_use integer,
    punderide integer,
    pimpact1 integer,
    pveh_sev integer,
    ptowed integer,
    pm_harm integer,
    pveh_sc1 integer,
    pveh_sc2 integer,
    pfire integer,
    pdeaths integer,
    ptrlr1vin text,
    ptrlr2vin text,
    ptrlr3vin text,
    constraint parkwork_pk primary key (st_case, veh_no)
);

CREATE TABLE pbtype (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    pbptype integer,
    pbage integer,
    pbsex integer,
    pbcwalk integer,
    pbswalk integer,
    pbszone integer,
    pedctype integer,
    bikectype integer,
    pedloc integer,
    bikeloc integer,
    pedpos integer,
    bikepos integer,
    peddir integer,
    bikedir integer,
    motdir integer,
    motman integer,
    pedleg integer,
    pedsnr text,
    pedcgp integer,
    bikecgp integer,
    constraint pbtype_pk primary key (st_case, per_no)
);

CREATE TABLE person (
    state integer,
    st_case integer,
    ve_forms integer,
    veh_no integer,
    per_no integer,
    str_veh integer,
    county integer,
    day integer,
    month integer,
    hour integer,
    minute integer,
    rur_urb integer,
    func_sys integer,
    harm_ev integer,
    man_coll integer,
    sch_bus integer,
    make integer,
    mak_mod integer,
    body_typ integer,
    mod_year integer,
    tow_veh integer,
    spec_use integer,
    emer_use integer,
    rollover integer,
    impact1 integer,
    fire_exp integer,
    age integer,
    sex integer,
    per_typ integer,
    inj_sev integer,
    seat_pos integer,
    rest_use integer,
    rest_mis integer,
    air_bag integer,
    ejection integer,
    ej_path integer,
    extricat integer,
    drinking integer,
    alc_det integer,
    alc_status integer,
    atst_typ integer,
    alc_res integer,
    drugs integer,
    drug_det integer,
    dstatus integer,
    drugtst1 integer,
    drugtst2 integer,
    drugtst3 integer,
    drugres1 integer,
    drugres2 integer,
    drugres3 integer,
    hospital integer,
    doa integer,
    death_da integer,
    death_mo integer,
    death_yr integer,
    death_hr integer,
    death_mn integer,
    death_tm integer,
    lag_hrs integer,
    lag_mins integer,
    p_sf1 integer,
    p_sf2 integer,
    p_sf3 integer,
    work_inj integer,
    hispanic integer ,
    race integer,
    location integer,
    constraint person_pk primary key (st_case, veh_no, per_no)
);

CREATE TABLE safetyeq (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    nmhelmet integer,
    nmpropad integer,
    nmothpro integer,
    nmrefclo integer,
    nmlight integer,
    nmothpre integer
);

-- This is the generated table code using the sqlite3 method; open the csv in sqlite, and dump the schema
CREATE TABLE vehicle (
   state text,
  statename text,
  st_case integer,
  veh_no  integer,
  ve_forms text,
  numoccs text,
  numoccsname text,
  day text,
  dayname text,
  month text,
  monthname text,
  hour text,
  hourname text,
  minute text,
  minutename text,
  harm_ev text,
  harm_evname text,
  man_coll text,
  man_collname text,
  unittype text,
  unittypename text,
  hit_run text,
  hit_runname text,
  reg_stat text,
  reg_statname text,
  owner text,
  ownername text,
  make text,
  makename text,
  model text,
  mak_mod text,
  mak_modname text,
  body_typ text,
  body_typname text,
  mod_year text,
  mod_yearname text,
  vin text,
  vinname text,
  vin_1 text,
  vin_2 text,
  vin_3 text,
  vin_4 text,
  vin_5 text,
  vin_6 text,
  vin_7 text,
  vin_8 text,
  vin_9 text,
  vin_10 text,
  vin_11 text,
  vin_12 text,
  tow_veh text,
  tow_vehname text,
  j_knife text,
  j_knifename text,
  mcarr_i1 text,
  mcarr_i1name text,
  mcarr_i2 text,
  mcarr_i2name text,
  mcarr_id text,
  mcarr_idname text,
  v_config text,
  v_configname text,
  cargo_bt text,
  cargo_btname text,
  haz_inv text,
  haz_invname text,
  haz_plac text,
  haz_placname text,
  haz_id text,
  haz_idname text,
  haz_cno text,
  haz_cnoname text,
  haz_rel text,
  haz_relname text,
  bus_use text,
  bus_usename text,
  spec_use text,
  spec_usename text,
  emer_use text,
  emer_usename text,
  trav_sp text,
  trav_spname text,
  underide text,
  underidename text,
  rollover text,
  rollovername text,
  rolinloc text,
  rolinlocname text,
  impact1 text,
  impact1name text,
  deformed text,
  deformedname text,
  towed text,
  towedname text,
  m_harm text,
  m_harmname text,
  fire_exp text,
  fire_expname text,
  dr_pres text,
  dr_presname text,
  l_state text,
  l_statename text,
  dr_zip text,
  dr_zipname text,
  l_status text,
  l_statusname text,
  l_type text,
  l_typename text,
  cdl_stat text,
  cdl_statname text,
  l_endors text,
  l_endorsname text,
  l_compl text,
  l_complname text,
  l_restri text,
  l_restriname text,
  dr_hgt text,
  dr_hgtname text,
  dr_wgt text,
  dr_wgtname text,
  prev_acc text,
  prev_accname text,
  prev_sus1 text,
  prev_sus1name text,
  prev_sus2 text,
  prev_sus2name text,
  prev_sus3 text,
  prev_sus3name text,
  prev_dwi text,
  prev_dwiname text,
  prev_spd text,
  prev_spdname text,
  prev_oth text,
  prev_othname text,
  first_mo text,
  first_moname text,
  first_yr text,
  first_yrname text,
  last_mo text,
  last_moname text,
  last_yr text,
  last_yrname text,
  speedrel text,
  speedrelname text,
  vtrafway text,
  vtrafwayname text,
  vnum_lan text,
  vnum_lanname text,
  vspd_lim text,
  vspd_limname text,
  valign text,
  valignname text,
  vprofile text,
  vprofilename text,
  vpavetyp text,
  vpavetypname text,
  vsurcond text,
  vsurcondname text,
  vtrafcon text,
  vtrafconname text,
  vtcont_f text,
  vtcont_fname text,
  p_crash1 text,
  p_crash1name text,
  p_crash2 text,
  p_crash2name text,
  p_crash3 text,
  p_crash3name text,
  pcrash4 text,
  pcrash4name text,
  pcrash5 text,
  pcrash5name text,
  acc_type text,
  acc_typename text,
  deaths text,
  dr_drink text,
  dr_drinkname text,
  trlr1vin text,
  trlr1vinname text,
  trlr2vin text,
  trlr2vinname text,
  trlr3vin text,
  trlr3vinname text,
  vpicmake text,
  vpicmakename text,
  vpicmodel text,
  vpicmodelname text,
  vpicbodyclass text,
  vpicbodyclassname text,
  icfinalbody text,
  icfinalbodyname text,
  gvwr_from text,
  gvwr_fromname text,
  gvwr_to text,
  gvwr_toname text,
  trlr1gvwr text,
  trlr1gvwrname text,
  trlr2gvwr text,
  trlr2gvwrname text,
  trlr3gvwr text,
  trlr3gvwrname text,
    constraint vehicle_pk primary key (st_case, veh_no)
);

CREATE TABLE vevent (
    state integer,
    st_case integer,
    eventnum integer,
    veh_no integer,
    veventnum integer,
    vnumber1 integer,
    aoi1 integer,
    soe integer,
    vnumber2 integer,
    aoi2 integer,
    constraint vevent_pk primary key (st_case, veh_no, eventnum)
);

CREATE TABLE vindecode (
    state integer,
    st_case integer,
    veh_no integer,
    ncicmake text,
    vinyear integer,
    vehtype text,
    vehtype_t text,
    vinmake_t text,
    vinmodel_t text,
    vintrim_t text,
    vintrim1_t text,
    vintrim2_t text,
    vintrim3_t text,
    vintrim4_t text,
    bodystyl text,
    bodystyl_t text,
    doors integer,
    wheels integer,
    drivwhls integer,
    mfg text,
    mfg_t text,
    displci integer,
    displcc integer,
    cylndrs text,
    cycles integer,
    fuel text,
    fuel_t text,
    fuelinj text,
    fuelinj_t text,
    carbtype text,
    carbtype_t text,
    carbbrls text,
    gvwrange integer,
    gvwrange_t text,
    whlbsh double precision,
    whlblg double precision,
    tiredesc_f text,
    psi_f integer,
    tiresz_f text,
    tiresz_f_t text,
    tiredesc_r text,
    psi_r integer,
    rearsize text,
    rearsize_t text,
    tonrating text,
    shipweight integer,
    msrp integer,
    drivetyp text,
    drivetyp_t text,
    salectry text,
    salectry_t text,
    abs text,
    abs_t text,
    security text,
    security_t text,
    drl text,
    drl_t text,
    rstrnt text,
    rstrnt_t text,
    tkcab text,
    tkcab_t text,
    tkaxlef text,
    tkaxlef_t text,
    tkaxler text,
    tkaxler_t text,
    tkbrak text,
    tkbrak_t text,
    engmfg text,
    engmfg_t text,
    engmodel text,
    tkduty text,
    tkduty_t text,
    tkbedl text,
    tkbedl_t text,
    segmnt text,
    segmnt_t text,
    plant text,
    plntctry_t text,
    plntcity text,
    plntctry text,
    plntstat text,
    plntstat_t text,
    origin text,
    origin_t text,
    dispclmt double precision,
    blocktype text,
    enghead text,
    enghead_t text,
    vlvclndr integer,
    vlvtotal integer,
    engvincd text,
    incomplt boolean,
    battyp text,
    battyp_t text,
    batkwrtg text,
    batvolt double precision,
    supchrgr text,
    supchrgr_t text,
    turbo text,
    turbo_t text,
    engvvt text,
    mcyusage text,
    mcyusage_t text,
    constraint vindecode_pk primary key (st_case, veh_no)
);

CREATE TABLE violatn (
    state integer,
    st_case integer,
    veh_no integer,
    mviolatn integer
);

CREATE TABLE vision (
    state integer,
    st_case integer,
    veh_no integer,
    mvisobsc integer
);

CREATE TABLE vsoe (
    state integer,
    st_case integer,
    veh_no integer,
    veventnum integer,
    soe integer,
    aoi integer,
    constraint vsoe_pk primary key (st_case, veh_no, veventnum)
);
